In [93]:
import pandas as pd

In [94]:
df=pd.read_csv('manual_match_id.csv')
df.shape

(1790, 6)

In [95]:
df=df.drop_duplicates('match_id')
df

,match_id,start_time,win,hero_id,account_id,leaguename
0,4061660411,1534348935,True,7,101356886,The International 2018
10,4061662358,1534349027,True,73,111620041,The International 2018
20,4061671194,1534349467,False,20,26771994,The International 2018
30,4061694810,1534351207,True,94,129958758,The International 2018
40,4061721528,1534352908,True,10,311360822,The International 2018
50,4061742840,1534354028,True,63,43276219,The International 2018
60,4061745637,1534354206,False,3,114239371,The International 2018
70,4061766981,1534355588,True,9,89871557,The International 2018
80,4061802430,1534357787,False,8,87285329,The International 2018
90,4061804100,1534357894,False,37,113800818,The International 2018
100,4061815647,1534358653,False,86,89117038,The International 2018
110,4061848287,1534360836,False,108,187619311,The International 2018
120,4061858332,1534361512,False,23,89423756,The International 2018
130,4061867364,1534362095,False,56,86698277,The International 2018
140,4061880066,1534362983,False,3,117731777,The International 2018
150,4061903681,1534364673,True,56,117281554,The International 2018
160,4061921764,1534365921,False,54,130416036,The International 2018
170,4061922574,1534365980,True,4,113457795,The International 2018
180,4061924528,1534366122,True,25,137272985,The International 2018
190,4061952570,1534368328,True,88,101356886,The International 2018
200,4061971770,1534369970,True,72,130416036,The International 2018
210,4061977166,1534370460,True,95,89871557,The International 2018
220,4061984521,1534371166,False,61,139937922,The International 2018
230,4062010988,1534373794,True,53,72312627,The International 2018
240,4062016236,1534374334,True,88,139876032,The International 2018
250,4062017242,1534374439,True,9,187619311,The International 2018
260,4062034566,1534376395,True,66,134556694,The International 2018
270,4062045592,1534377651,False,103,89423756,The International 2018
280,4062047269,1534377847,False,11,116585378,The International 2018
290,4062061780,1534379457,False,11,106573901,The International 2018
...,...,...,...,...,...,...
1490,4070423361,1534791992,True,61,72312627,The International 2018
1500,4070500759,1534796227,False,19,106573901,The International 2018
1510,4070556816,1534800190,True,109,125581247,The International 2018
1520,4070612749,1534804707,False,70,43276219,The International 2018
1530,4070674710,1534810174,False,107,155494381,The International 2018
1540,4070746269,1534815802,True,19,250114507,The International 2018
1550,4070838238,1534821698,True,75,113800818,The International 2018
1560,4072252473,1534873367,True,22,94054712,The International 2018
1570,4072354014,1534878322,True,112,26771994,The International 2018
1580,4072441405,1534883048,False,112,87278757,The International 2018
1590,4072509593,1534887572,True,63,41231571,The International 2018
1600,4072586507,1534894099,False,103,138543123,The International 2018
1610,4072635180,1534898196,False,17,157475523,The International 2018
1620,4072699199,1534902846,True,56,132851371,The International 2018
1630,4072772695,1534907661,False,42,84772440,The International 2018
1640,4074178274,1534959427,False,63,130801103,The International 2018
1650,4074255285,1534963179,False,96,130801103,The International 2018
1660,4074356696,1534968491,True,65,134276083,The International 2018
1670,4074440208,1534973895,False,75,113800818,The International 2018
1680,4074486307,1534977517,False,111,113800818,The International 2018
1690,4074591870,1534986664,True,3,94296097,The International 2018
1700,4074639753,1534990401,True,75,94296097,The International 2018
1710,4074694505,1534994296,False,12,86745912,The International 2018
1720,4074748928,1534997864,True,6,86745912,The International 2018
1730,4074821374,1535002214,True,67,311360822,The International 2018
1740,4076043995,1535046106,False,49,106573901,The International 2018
1750,4076114893,1535049678,False,73,221666230,The International 2018
1760,4076188379,1535053843,False,56,87285329,The International 2018
1770,4076257095,1535058023,False,46,108452107,The International 2018
1780,4076314248,1535061995,True,75,87278757,The International 2018

In [96]:

df.drop(df.iloc[:, 1:6], inplace=True, axis=1)

In [97]:
df

        match_id
0     4061660411
10    4061662358
20    4061671194
30    4061694810
40    4061721528
50    4061742840
60    4061745637
70    4061766981
80    4061802430
90    4061804100
100   4061815647
110   4061848287
120   4061858332
130   4061867364
140   4061880066
150   4061903681
160   4061921764
170   4061922574
180   4061924528
190   4061952570
200   4061971770
210   4061977166
220   4061984521
230   4062010988
240   4062016236
250   4062017242
260   4062034566
270   4062045592
280   4062047269
290   4062061780
...          ...
1490  4070423361
1500  4070500759
1510  4070556816
1520  4070612749
1530  4070674710
1540  4070746269
1550  4070838238
1560  4072252473
1570  4072354014
1580  4072441405
1590  4072509593
1600  4072586507
1610  4072635180
1620  4072699199
1630  4072772695
1640  4074178274
1650  4074255285
1660  4074356696
1670  4074440208
1680  4074486307
1690  4074591870
1700  4074639753
1710  4074694505
1720  4074748928
1730  4074821374
1740  4076043995
1750  4076114893
1760  4076188379
1770  4076257095
1780  4076314248

[179 rows x 1 columns]

In [98]:
df.to_csv("match_ids.csv", index = False)