In [10]:
import pandas as pd

In [12]:
df=pd.read_csv('premium3')
df.shape

(4400, 6)

In [13]:
df=df.drop_duplicates('match_id')
df

,match_id,start_time,win,hero_id,account_id,leaguename
0,3962882047,1529481203,True,75,117731777,The International 2018
10,3962997393,1529486506,False,4,168028715,The International 2018
20,3963082795,1529490182,False,85,140153524,The International 2018
30,3963141136,1529492533,True,30,94049589,The International 2018
40,3963175050,1529493843,False,85,140153524,The International 2018
50,3963261456,1529497123,True,87,90125566,The International 2018
60,3963365795,1529500670,False,79,94049589,The International 2018
70,3963510721,1529505283,True,101,93552791,The International 2018
80,3963622811,1529508966,False,101,93552791,The International 2018
90,3963695407,1529511676,True,16,157989498,The International 2018
100,3963748898,1529513983,True,89,93552791,The International 2018
110,3963766315,1529514677,True,16,84853828,The International 2018
120,3963833718,1529517802,True,112,86974263,The International 2018
130,3963951879,1529524041,True,60,242697694,The International 2018
140,3964015955,1529527623,False,16,157989498,The International 2018
150,3964347005,1529553394,False,52,163587550,The International 2018
160,3964420417,1529557940,False,11,248941611,The International 2018
170,3964501224,1529562571,False,3,849035415,The International 2018
180,3964587511,1529567163,False,37,849035415,The International 2018
190,3964610577,1529568056,False,89,182993582,The International 2018
200,3964678461,1529571227,False,37,94049589,The International 2018
210,3964779866,1529575645,True,64,94049589,The International 2018
220,3964906211,1529580746,False,37,90125566,The International 2018
230,3965026783,1529584972,False,87,94049589,The International 2018
240,3965138122,1529588653,False,87,94049589,The International 2018
250,3965322615,1529594522,True,3,90125566,The International 2018
260,3965388783,1529597019,False,2,242697694,The International 2018
270,3965452132,1529599687,True,66,93552791,The International 2018
280,3965513793,1529602408,False,2,242697694,The International 2018
290,3965525689,1529602946,False,87,90125566,The International 2018
...,...,...,...,...,...,...
4100,4074255285,1534963179,True,110,86726887,The International 2018
4110,4074356696,1534968491,False,66,87278757,The International 2018
4120,4074440208,1534973895,True,66,87278757,The International 2018
4130,4074486307,1534977517,False,56,137193239,The International 2018
4140,4074591870,1534986664,False,31,82262664,The International 2018
4150,4074639753,1534990401,False,85,82262664,The International 2018
4160,4074694505,1534994296,False,46,111620041,The International 2018
4170,4074748928,1534997864,False,75,19672354,The International 2018
4180,4074821374,1535002214,False,19,111620041,The International 2018
4190,4076043995,1535046106,True,59,221666230,The International 2018
4200,4076114893,1535049678,False,73,221666230,The International 2018
4210,4076188379,1535053843,True,53,134556694,The International 2018
4220,4076257095,1535058023,True,75,87278757,The International 2018
4230,4076314248,1535061995,True,75,87278757,The International 2018
4240,4076431752,1535071847,False,5,134556694,The International 2018
4250,4076485641,1535075729,True,73,111620041,The International 2018
4260,4078079157,1535132746,False,66,87278757,The International 2018
4270,4078180258,1535137622,False,66,87278757,The International 2018
4280,4078291886,1535143603,False,6,125581247,The International 2018
4290,4078363316,1535148299,False,75,19672354,The International 2018
4300,4078412913,1535152122,True,75,19672354,The International 2018
4310,4078478649,1535157660,True,17,111620041,The International 2018
4320,4078566725,1535163554,True,98,111620041,The International 2018
4330,4080316101,1535219083,False,73,111620041,The International 2018
4340,4080420268,1535223496,True,48,125581247,The International 2018
4350,4080601137,1535231302,True,112,19672354,The International 2018
4360,4080666526,1535235390,True,12,125581247,The International 2018
4370,4080723031,1535239468,False,66,19672354,The International 2018
4380,4080778303,1535243738,False,10,125581247,The International 2018
4390,4080856812,1535249730,False,109,125581247,The International 2018

In [14]:

df.drop(df.iloc[:, 1:6], inplace=True, axis=1)

In [15]:
df

        match_id
0     3962882047
10    3962997393
20    3963082795
30    3963141136
40    3963175050
50    3963261456
60    3963365795
70    3963510721
80    3963622811
90    3963695407
100   3963748898
110   3963766315
120   3963833718
130   3963951879
140   3964015955
150   3964347005
160   3964420417
170   3964501224
180   3964587511
190   3964610577
200   3964678461
210   3964779866
220   3964906211
230   3965026783
240   3965138122
250   3965322615
260   3965388783
270   3965452132
280   3965513793
290   3965525689
...          ...
4100  4074255285
4110  4074356696
4120  4074440208
4130  4074486307
4140  4074591870
4150  4074639753
4160  4074694505
4170  4074748928
4180  4074821374
4190  4076043995
4200  4076114893
4210  4076188379
4220  4076257095
4230  4076314248
4240  4076431752
4250  4076485641
4260  4078079157
4270  4078180258
4280  4078291886
4290  4078363316
4300  4078412913
4310  4078478649
4320  4078566725
4330  4080316101
4340  4080420268
4350  4080601137
4360  4080666526
4370  4080723031
4380  4080778303
4390  4080856812

[440 rows x 1 columns]

In [16]:
df.to_csv("match_ids.csv", index = False)